window.Scenes = [
  {
    id: "intro",
    transition: "click",
    cursor: "default",
    tooltipVisible: true,
    cursorTooltip: "In the recesses of my memory I relive certain scenes",
    blocks: [
      { x: 1, y: 1, visible: true, image: "img0.png", hoverCursor: "zoom-in", hoverTooltip: "An image appears in my mind", clickable: true },
    ],
  },
  {
    id: "intro",
    transition: "click",
    cursor: "default",
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 1, visible: true, image: "img1.jpeg", hoverCursor: "nesw-resize", clickable: true },
    ],
    },

  {
    id: "image-appears",
    transition: "auto",
    transitionStyle: "slide",
    slideDuration: 1.2,
    autoDuration: 1600,
    delay: true,
    bottomText: "What do you remember from that moment?",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "img1.jpeg"},
    ],
  },

  {
    id: "image-changes",
    transition: "auto",
    transitionStyle: "slide",
    slideDuration: 1.2,
    autoDuration: 1600,
    bottomText: "What do you remember from that moment?",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "img2.jpeg" },
    ],
  },

  {
    id: "image-appears",
    transition: "auto",
    autoDuration: 2500,
    transitionStyle: "slide",
    slideDuration: 1.2,
    bottomText: "What do you remember from that moment?",
    cursor: "default",
    tooltipVisible: false,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "img3.jpeg"},
    ],
  },
  {
    id: "image-appears",
    transition: "click",
    bottomText: "What do you remember from that moment?",
    cursor: "zoom-out",
    cursorTooltip: "I think I was looking through a window",
    tooltipVisible: true,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "img3.jpeg"},
    ],
  },
  {
    id: "image-changes",
    transition: "auto",
    autoDuration: 400,
    bottomText: "",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [

    ],
  },
  {
    id: "image-changes",
    transition: "auto", 
    autoDuration: 400,
    cursor: "default",
    delay: true,
    bottomText: "Do you remember what time of day it was?",
    blocks: [
      { x: 0, y: 1, visible: true, image: "img1.jpeg"},
      { x: 1, y: 1, visible: true, image: "img2.jpeg"}, 
      { x: 2, y: 1, visible: true, image: "img3.jpeg"},
    ],
  },

  {
    id: "image-changes",
    transition: "click",
    cursor: "default",
    delay: true,
    bottomText: "Do you remember what time of day it was?",
    blocks: [
      { x: 0, y: 1, visible: true, image: "img1.jpeg", hoverCursor: "help", hoverTooltip: "The sun was setting", clickable: false},
      { x: 1, y: 1, visible: true, image: "img2.jpeg", hoverCursor: "help", hoverTooltip: "There was a waning light", clickable: false},
      { x: 2, y: 1, visible: true, image: "img3.jpeg", hoverCursor: "zoom-in", hoverTooltip: "Everything was bathed in gold", clickable: true},
    ],
  },

  {
    id: "image-changes",
    transition: "click",
    cursor: "default",
    delay: true,
    bottomText: "Do you remember what time of day it was?",
    blocks: [
      { x: 0, y: 1, visible: true, image: "img4.JPG", hoverCursor: "zoom-in", hoverTooltip: "The trees were golden too", clickable: true},
      { x: 1, y: 1, visible: true, image: "img5.jpeg", hoverCursor: "zoom-in", hoverTooltip: "The trees were golden too", clickable: true},
      { x: 2, y: 1, visible: true, image: "img6.JPG", hoverCursor: "zoom-in", hoverTooltip: "The trees were golden too", clickable: true},
    ],
  },

  {
    id: "zoom-out-different",
    transition: "click",
    bottomText: "What did you say exactly?",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 0, y: 1, visible: false, image: "img4.JPG"},
      { x: 1, y: 1, visible: false, image: "img5.jpeg"},
      { x: 2, y: 1, visible: true, image: "img6.JPG",
        hoverCursor: "help",
        hoverTooltip: "What did I say?",
        clickable: true,
      },    ],
  },

  {
    id: "next",
    transition: "click",
    bottomText: "Do you remember what happens next?",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      {  x: 2, y: 1, visible: true, image: "img6.JPG"},
      {x: 1, y: 1, visible: false, image: "next/img4.jpeg", hoverCursor: "grabbing", hoverTooltip: "The outcome I want to change", clickable: true},
    ],
  },

  {
    id: "golden-hour",
    transition: "auto",
    autoDuration: 2000,
    bottomText: "They say that once you remember fully you can travel back in time",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 1, visible: true, image: "next/img4.jpeg" },
    ],
  },

  {
    id: "spotlight-you",
    transition: "auto",
    autoDuration: 3000,
    bottomText: "Photos are supposed to help with that",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      {  x: 2, y: 1, visible: true, image: "img6.JPG"},
      { x: 1, y: 1, visible: true, image: "next/img4.jpeg" }
    ],
  },

  {
    id: "spotlight-me",
    transition: "auto",
    autoDuration: 2500,
    delay: true,
    bottomText: "But not completely",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: true, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/img5.jpeg" },
      { x:0, y: 2, visible: true, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/img8.jpeg" },
      { x:2, y: 1, visible: true, image: "next/img9.jpeg"},
        ],
  },

  {
    id: "gaps",
    transition: "click",
    cursor: "default",
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg", hoverCursor: "pointer", hoverTooltip: "Sometimes there are gaps", clickable: true},
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/img5.jpeg" },
      { x:0, y: 2, visible: true, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/img8.jpeg" },
      { x:2, y: 1, visible: true, image: "next/img9.jpeg"},
        ],
  },
  {
    id: "pres",
    transition: "click",
    cursor: "default",
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/img5.jpeg" },
      { x:0, y: 2, visible: true, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/img8.jpeg" },
      { x:2, y: 1, visible: false, image: "next/img9.jpeg", hoverCursor: "not-allowed", hoverTooltip: "Breaking the connection to the present", clickable: true},
        ],
  },

  {
    id: "remember-fully",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    cursorTooltip: "the mind misremembers,",
    tooltipVisible: true,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: false, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/bw5.jpeg" },
      { x:0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/bw8.jpeg" },
      { x:2, y: 1, visible: true, image: "next/bw9.jpeg"},
        ],
  },
  {
    id: "remember-fully",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    cursorTooltip: "distorts, remembers through",
    tooltipVisible: true,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: false, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/bw5.jpeg" },
      { x:0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/bw8.jpeg" },
      { x:2, y: 1, visible: true, image: "next/bw9.jpeg"},
        ],
  },
  {
    id: "remember-fully",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    cursorTooltip: "smudged lens",
    tooltipVisible: true,
    blocks: [
      { x: 1, y: 0, visible: true, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: false, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: true, image: "next/bw5.jpeg" },
      { x:0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: true, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: true, image: "next/bw8.jpeg" },
      { x:2, y: 1, visible: true, image: "next/bw9.jpeg"},
        ],
  },

  {
    id: "remember-fully",
    transition: "click",
    cursor: "wait",
    bottomText: "You're still there aren't you?",
    tooltipVisible: false,
    blocks: [
      { x: 1, y: 0, visible: false, image: "next/img2.jpeg" },
      { x: 1, y: 2, visible: false, image: "next/img1.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/img4.jpeg", hoverCursor: "help", clickable: true },
      { x: 0, y: 1, visible: false, image: "next/img3.jpeg" },
      { x:0, y: 0, visible: false, image: "next/bw5.jpeg"},
      { x:0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x:2, y: 0, visible: false, image: "next/img6.jpeg" },
      { x:2, y: 2, visible: false, image: "next/bw8.jpeg" },
      { x:2, y: 1, visible: false, image: "next/bw9.jpeg"},
        ],
  },

  {
    id: "remember-fully",
    transition: "click",
    cursor: "wait",
    bottomText: "Shouldn’t you have learned by now?",
    tooltipVisible: false,
    blocks: [

      { x: 0, y: 1, visible: true, image: "shuffle/img1.jpeg", hoverCursor: "help", clickable: true },
      { x:2, y: 0, visible: true, image: "shuffle/img2.jpeg", hoverCursor: "help", clickable: true },
      { x:1, y: 2, visible: true, image: "shuffle/img3.jpeg", hoverCursor: "help", clickable: true },

        ],
  },

  {
    id: "gaps-hide-between",
    transition: "click",
    bottomText: "You're always looking back for an answer to your questions",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x:1, y: 1, visible: true, image: "shuffle/center.jpeg", hoverCursor: "zoom-in", clickable: true },
    ],
  },

  {
    id: "change",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    tooltipVisible: true,
    cursorTooltip: "But everything keeps changing",
    blocks:   [
      { x: 2, y: 2, visible: true, image: "next/img6.jpeg" },
      { x: 0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x: 1, y: 1, visible: true, image: "next/bw5.jpeg" },
      { x: 1, y: 0, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x: 2, y: 0, visible: false, image: "next/bw9.jpeg" },
      { x: 2, y: 1, visible: false, image: "next/img2.jpeg" },
      { x: 0, y: 0, visible: true, image: "next/bw8.jpeg" },
      { x: 1, y: 2, visible: false, image: "next/img1.jpeg" },
        ],
  },

  
  {
    id: "change",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    tooltipVisible: true,
    cursorTooltip: "But everything keeps changing",
    blocks:   [
      { x: 2, y: 2, visible: false, image: "next/img6.jpeg" },
      { x: 0, y: 2, visible: true, image: "next/img7.jpeg" },
      { x: 1, y: 1, visible: false, image: "next/bw5.jpeg" },
      { x: 1, y: 0, visible: true, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: false, image: "next/img3.jpeg" },
      { x: 2, y: 0, visible: true, image: "next/bw9.jpeg" },
      { x: 2, y: 1, visible: true, image: "next/img2.jpeg" },
      { x: 0, y: 0, visible: false, image: "next/bw8.jpeg" },
      { x: 1, y: 2, visible: true, image: "next/img1.jpeg" },
        ],
  },

  {
    id: "change",
    transition: "auto",
    autoDuration: 2000,
    cursor: "wait",
    tooltipVisible: true,
    cursorTooltip: "But everything keeps changing",
    blocks:   [
      { x: 2, y: 2, visible: true, image: "next/img6.jpeg" },
      { x: 0, y: 2, visible: false, image: "next/img7.jpeg" },
      { x: 1, y: 1, visible: true, image: "next/bw5.jpeg" },
      { x: 1, y: 0, visible: false, image: "next/img4.jpeg" },
      { x: 0, y: 1, visible: true, image: "next/img3.jpeg" },
      { x: 2, y: 0, visible: false, image: "next/bw9.jpeg" },
      { x: 2, y: 1, visible: false, image: "next/img2.jpeg" },
      { x: 0, y: 0, visible: true, image: "next/bw8.jpeg" },
      { x: 1, y: 2, visible: false, image: "next/img1.jpeg" },
        ],
  },

  {
    id: "nothing chnages",
    transition: "auto",
    autoDuration: 2000,
    bottomText: "Look closer",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 2, y: 0, visible: true, image: "nothing/disco1.jpeg" },
      { x: 0, y: 2, visible: true, image: "nothing/disco2.jpeg" },
      { x: 1, y: 1, visible: true, image: "nothing/disco3.jpeg" },
      { x: 0, y: 0, visible: true, image: "nothing/disco4.jpeg" },
    ],
  },

  {
    id: "nothing chnages",
    transition: "auto",
    autoDuration: 2000,
    bottomText: "Look closer",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 0, y: 0, visible: true, image: "nothing/gate1.jpeg" },
      { x: 1, y: 0, visible: true, image: "nothing/gate2.jpeg" },
      { x: 2, y: 0, visible: true, image: "nothing/gate3.jpeg" },
    ],
  },

  {
    id: "nothing chnages",
    transition: "auto",
    autoDuration: 2000,
    bottomText: "Look closer",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 0, y: 0, visible: true, image: "nothing/shoes.jpeg" },
      { x: 2, y: 2, visible: true, image: "nothing/shoes1.jpeg" },
    ],
  },

  {
    id: "nothing chnages",
    transition: "auto",
    autoDuration: 2000,
    bottomText: "Look closer",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    blocks: [
      { x: 0, y: 0, visible: true, image: "nothing/sun1.JPG" },
      { x: 2, y: 0, visible: true, image: "nothing/sun2.jpeg" },
      { x: 0, y: 2, visible: true, image: "nothing/sun3.jpeg" },
    ],
  },
  {
    id: "nothing-flash",
    transition: "click",
    bottomText: "Nothing changes",
    cursor: "zoom-in",
    tooltipVisible: false,
    flashSequence: {
      interval: 200,
      images: ["img1.jpeg", "img2.jpeg", "img3.jpeg", "img4.JPG", "img5.jpeg", "img6.JPG", "next/img8.jpeg",
        "next/img1.jpeg", "next/img2.jpeg", "next/img3.jpeg", "next/img4.jpeg", "next/img5.jpeg",
        "nothing/sun1.JPG", "nothing/sun2.jpeg", "nothing/sun3.jpeg",
        "nothing/disco1.jpeg", "nothing/disco2.jpeg", "nothing/disco3.jpeg",
        "nothing/gate1.jpeg", "nothing/gate2.jpeg", "nothing/gate3.jpeg",
        "nothing/shoes.jpeg", "nothing/shoes1.jpeg", "nothing/first.jpg",
      ],
    },
    blocks: [],
  },
  {
    id: "see-it-now",
    transition: "click",
    bottomText: "Don't you see it now?",
    cursor: "zoom-in",
    cursorTooltip: "",
    tooltipVisible: true,
    breakoutGrid: true,
    breakoutBackground: "bg.png",
    breakoutEndImage: "nothing/output.gif",
    breakoutAudio: "nothing/cropped.mp3",
    blocks: [],
  },

  {
    id: "image-appears",
    transition: "click",
    bottomText: "Yeah... I do",
    cursor: "help",
    cursorTooltip: null,
    tooltipVisible: false,
    persistAudio: true,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "nothing/output.gif"},
    ],
  },
  {
    id: "image-appears",
    transition: "auto",
    autoDuration: 800,
    bottomText: "Photos taken from my camera roll between 2020 and 2026",
    cursor: "default",
    cursorTooltip: null,
    tooltipVisible: false,
    persistAudio: true,
    zoom: 3,
    zoomCenter: { x: 1, y: 1 } ,
    blocks: [
      { x: 1, y: 1, visible: true, image: "nothing/output.gif"},
    ],
  }
];

Engine.start();
